[technote]
id = "SITCOMTN-029"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-029.lsst.io/"
github_url = "https://github.com/lsst-sitcom/sitcomtn-029"
github_default_branch = "main"
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"
[[technote.authors]]
name = {given = "Patrick", family = "Ingraham"}
internal_id = "ingrahamp"
orcid = "https://orcid.org/0000-0003-3715-8138"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"

[[technote.authors]]
name = {given = "Erik", family = "Dennihy"}
internal_id = "dennihye"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
